name: API Test CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Check out código
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip  # Atualiza o pip
        pip install -r requirements.txt  # Instala as dependências do projeto (garante que pytest esteja instalado)

    - name: Rodar testes
      run: |
        pytest tests/  # Executa os testes dentro da pasta tests
